#!/bin/bash

#Setup script for Dotfiles
echo -e "\u001b[32;1m Setting up Dotfiles...\u001b[0m"

echo -e " \u001b[37;1m\u001b[4mSelect an option:\u001b[0m"
echo -e "  \u001b[34;1m (1) Install oh-my-zsh \u001b[0m"
echo -e "  \u001b[34;1m (2) Install zsh plugins \u001b[0m"
echo -e "  \u001b[34;1m (4) Setup fonts \u001b[0m"
echo -e "  \u001b[34;1m (5) Setup symlinks \u001b[0m"
echo -e "  \u001b[34;1m (6) install dwm related files (install dwm first!) \u001b[0m"
echo -e "  \u001b[31;1m (0) Exit \u001b[0m"

echo -en "\u001b[32;1m ==> \u001b[0m"

read -r option

case $option in

"1")echo -e "\u001b[7m Installing oh-my-zsh...\u001b[0m"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    ;;

"2")echo -e "\u001b[7m Installing zsh plugins...\u001b[0m"
    git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips
    ;;

"4")echo -e "\u001b[7m Setting up fonts... \u001b[0m"
    for fname in "DejaVuSansMono" "DroidSansMono"; do
	mkdir ~/.fonts
        wget -O ~/.fonts/$fname.zip  https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/$fname.zip
        unzip -u ~/.fonts/$fname.zip -d ~/.fonts/$fname
        rm -f ~/.fonts/$fname.zip
    done
    fc-cache -fv
    ;;

"5")echo -e "\u001b[7m Setting up symlinks... \u001b[0m"
    echo -e "\u001b[33;1m Backup existing files? (y/n) \u001b[0m"
    read -r backupOption
    if [[ $backupOption == "y" ]]; then
        echo -e "\u001b[33;1m Backing up existing files... \u001b[0m"
        mv -iv ~/.Xmodmap ~/.Xmodmap.old
        mv -iv ~/.config/htop ~/.config/htop.old
        mv -iv ~/.config/nvim ~/.config/nvim.old
        mv -iv ~/.config/ranger ~/.config/ranger.old
        mv -iv ~/.config/yazi ~/.config/yazi.old
        mv -iv ~/.zshrc ~/.zshrc.old
        mv -iv ~/.p10k.zsh ~/.p10k.zsh.old
        mv -iv ~/.profile ~/.profile.old
        mv -iv ~/.xprofile ~/.xprofile.old
        echo -e "\u001b[36;1m Remove backups with 'rm -ir ~/.*.old && rm -ir ~/.config/*.old'. \u001b[0m"
    else
        echo -e "\u001b[36;1m Skipping backups. \u001b[0m"
    fi

    echo -e "\u001b[36;1m Adding symlinks...\u001b[0m"
    ln -sfnv "$PWD/.Xmodmap" ~/.Xmodmap
    ln -sfnv "$PWD/.config/htop/" ~/.config/htop
    ln -sfnv "$PWD/.config/ranger/" ~/.config/ranger
    ln -sfnv "$PWD/.config/yazi/" ~/.config/yazi
    ln -sfnv "$PWD/.config/nvim/" ~/.config/nvim
    ln -sfnv "$PWD/.config/git/" ~/.config/git
    ln -sfnv "$PWD/.zshrc" ~/.zshrc
    ln -sfnv "$PWD/.p10k.zsh" ~/.p10k.zsh
    ln -sfnv  "$PWD/Scripts/.local/.bin/" ~/.local/bin
    chmod +x ~/.local/bin/statusbar/*
    chmod +x ~/.local/bin/**/*.sh
    ln -sfnv "$PWD/.profile-linux" ~/.profile
    ln -sfnv "$PWD/.xprofile" ~/.xprofile
    ;;
"6")echo -e "\u001b[7m Installing dwm related filed... \u001b[0m"
    ln -sfnv  "$PWD/dwm/dwm-presonalized" /usr/local/bin
    chmod +x "$PWD/dwm/dwm-presonalized"
    cp  "$PWD/dwm/dwm.desktop" /usr/share/xsessions/
    ln -sfnv "$PWD/dwm/startup.sh" ~/.dwm_startup
    sudo ln -sfnv "$PWD/dwm/startup.sh" /usr/share/xsessions/dwm_startup.sh
    chmod 755 /usr/share/xsessions/dwm_startup.sh
    sudo ln -sfnv "$PWD/dwm/dwm.desktop" /usr/share/xsessions/dwm.desktop
    ;;
"0")echo -e "\u001b[32;1m Bye! \u001b[0m"
    exit 0
    ;;

*)echo -e "\u001b[31;1m Invalid option entered! \u001b[0m"
    exit 1
    ;;
esac

exit 0
