#!/bin/bash

#Setup script for Dotfiles
echo -e "\u001b[32;1m Setting up Dotfiles...\u001b[0m"

echo -e " \u001b[37;1m\u001b[4mSelect an option:\u001b[0m"
echo -e "  \u001b[34;1m (1) Install oh-my-zsh \u001b[0m"
echo -e "  \u001b[34;1m (2) Install zsh plugins \u001b[0m"
echo -e "  \u001b[34;1m (5) Setup symlinks \u001b[0m"
echo -e "  \u001b[34;1m (6) install cheat.sh \u001b[0m"
echo -e "  \u001b[34;1m (7) install dwm related files (install dwm first!) \u001b[0m"
echo -e "  \u001b[31;1m (0) Exit \u001b[0m"

echo -en "\u001b[32;1m ==> \u001b[0m"

read -r option

case $option in

"1")echo -e "\u001b[7m Installing oh-my-zsh...\u001b[0m"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    ;;

"2")echo -e "\u001b[7m Installing zsh plugins...\u001b[0m"
    git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    git clone https://github.com/zdharma/fast-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
    git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    ;;

"5")echo -e "\u001b[7m Setting up symlinks... \u001b[0m"
    echo -e "\u001b[33;1m Backup existing files? (y/n) \u001b[0m"
    read -r backupOption
    if [[ $backupOption == "y" ]]; then
        echo -e "\u001b[33;1m Backing up existing files... \u001b[0m"
        mv -iv ~/.Xresources ~/.Xresources.old
        mv -iv ~/.Xmodmap ~/.Xmodmap.old
        mv -iv ~/.config/htop ~/.config/htop.old
        mv -iv ~/.config/ranger ~/.config/ranger.old
        mv -iv ~/.dmenurc ~/.dmenurc.old
        mv -iv ~/.gitconfig ~/.gitconfig.old
        mv -iv ~/.zshrc ~/.zshrc.old
        mv -iv ~/.p10k.zsh ~/.p10k.zsh.old
        echo -e "\u001b[36;1m Remove backups with 'rm -ir ~/.*.old && rm -ir ~/.config/*.old'. \u001b[0m"
    else
        echo -e "\u001b[36;1m Skipping backups. \u001b[0m"
    fi

    echo -e "\u001b[36;1m Adding symlinks...\u001b[0m"
    ln -sfnv "$PWD/.Xresources" ~/.Xresources
    ln -sfnv "$PWD/.Xmodmap" ~/.Xmodmap
    ln -sfnv "$PWD/.config/htop/" ~/.config/htop
    ln -sfnv "$PWD/.config/ranger/" ~/.config/ranger
    ln -sfnv "$PWD/.config/nvim/" ~/.config/nvim
    #ln -sfnv "$PWD/.dmenurc" ~/.dmenurc
    ln -sfnv "$PWD/.gitconfig" ~/.gitconfig
    if [ ! -f ~/.config/nvim/init.vim.local ]; then
        cp ~/.config/nvim/init.vim.def.local ~/.config/nvim/init.vim.local
    fi
    ln -sfnv "$PWD/.zshrc" ~/.zshrc
    ln -sfnv "$PWD/.p10k.zsh" ~/.p10k.zsh
    ln -sfnv  "$PWD/Scripts/.local/.bin/statusbar/*" ~/bin
    chmod +x ~/bin/sb-*
    sudo $SHELL -c 'cat "$PWD/etc/environment" >> /etc/environment'
    ;;
"6")echo -e "\u001b[7m Installing cheat.sh... \u001b[0m"
    mkdir -p ~/bin
    curl https://cht.sh/:cht.sh > ~/bin/cheet.sh
    chmod +x ~/bin/cheet.sh
    ;;
"7")echo -e "\u001b[7m Installing dwm related filed... \u001b[0m"
    ln -sfnv  "$PWD/dwm/dwm-presonalized" /usr/local/bin
    chmod +x "$PWD/dwm/dwm-presonalized"
    cp  "$PWD/dwm/dwm.desktop" /usr/share/xsessions/
    ;;
"0")echo -e "\u001b[32;1m Bye! \u001b[0m"
    exit 0
    ;;

*)echo -e "\u001b[31;1m Invalid option entered! \u001b[0m"
    exit 1
    ;;
esac

exit 0
