#!/bin/bash

case $BUTTON in
	3) notify-send "CPU and MEM module" "Show CPU temparatur and memory" ;;
  6) bash -c "$TERMINAL -e \"$EDITOR $0\"" ;;
esac

memory=$(free -h | awk '/^Память/ { print $3"/"$2 }' | sed s/i//g)
temp=$(sensors | awk '/^Package/ { print $4 }')
temp=$(echo ${temp:1:-4}"°C")

printf "%s %s" "$temp" "$memory"
